{% set name = "stactools" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stactools-{{ version }}.tar.gz
  sha256: f305b78ce761649f563b2cdd6aabdbf34db613ff93fde5c4c5b8cc280abccb91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - stac = stactools.cli.cli:run_cli

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - aiohttp >=3.8.3
    - click >=8.1.3
    - fsspec >=2021.7
    - lxml >=4.9.2
    - numpy >=1.22.0
    - pyproj >=3.3
    - pystac >=1.6.1
    - python >=3.8
    - rasterio >=1.3.2
    - requests >=2.27.1
    - shapely >=1.8.5.post1
    - stac-check >=1.3.2
    - stac-validator >=3.1.0

test:
  imports:
    - stactools
  commands:
    - pip check
    - stac --help
  requires:
    - pip

about:
  home: https://github.com/stac-utils/stactools
  summary: Command line tool and Python library for working with STAC
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://stactools.readthedocs.io/en/stable/
  dev_url: https://github.com/stac-utils/stactools

extra:
  recipe-maintainers:
    - gadomski
