{% set name = "stactools" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stactools-{{ version }}.tar.gz
  sha256: 6bb10952d3219d023c023be637e8d714789763597d664b097e72b7e3ad8b4327

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - stac = stactools.cli.cli:run_cli

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - aiohttp >=3.8
    - click >=8.1.3
    - fsspec >=2021.7
    - lxml >=4.6
    - numpy >=1.21.0
    - pyproj >=3.0
    - pystac >=1.2
    - python >=3.7
    - rasterio >=1.2.9
    - requests >=2.20
    - shapely >=1.6
    - stac-check >=1.2.0
    - stac-validator >=3.1.0

test:
  imports:
    - stactools
  commands:
    - pip check
    - stac --help
  requires:
    - pip

about:
  home: https://github.com/stac-utils/stactools
  summary: Command line tool and Python library for working with STAC
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://stactools.readthedocs.io/en/stable/
  dev_url: https://github.com/stac-utils/stactools

extra:
  recipe-maintainers:
    - gadomski
